name: Test Dotfiles
on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '0 8 * * 6'

jobs:
  test:
    strategy:
      matrix:
        include:
          - name: macOS
            os: macos-latest
          - name: Ubuntu
            os: ubuntu-latest
      fail-fast: false

    name: Test on ${{ matrix.name }}
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Install 1Password CLI
        uses: 1password/install-cli-action@v1

      - name: Set up chezmoi
        id: cache-chezmoi
        uses: actions/cache@v4
        with:
          path: ~/bin/chezmoi
          key: ${{ runner.os }}-chezmoi-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-chezmoi-
      - name: Install chezmoi
        run: |
          mkdir -p ~/bin
          if [ ! -f ~/bin/chezmoi ] || [ "${{ steps.cache-chezmoi.outputs.cache-hit }}" != 'true' ]; then
            echo "Installing chezmoi..."
            sh -c "$(curl -fsLS get.chezmoi.io)" -- -b ~/bin
          else
            echo "Using cached chezmoi"
          fi
          ~/bin/chezmoi --version
          echo "$HOME/bin" >> $GITHUB_PATH

      - name: Create test directories
        run: |
          mkdir -p ~/test-home
          mkdir -p ~/test-home/workspace

      - name: Initialize chezmoi
        env:
          HOME: ~/test-home
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
        run: |
          # Create a temporary config file with test values
          mkdir -p ~/.config/chezmoi
          cat > ~/.config/chezmoi/chezmoi.toml << EOF
          [data]
            workspace = "$HOME/workspace"
            email = "test@example.com"
            name = "Test User"
          EOF
          chezmoi init --source=$GITHUB_WORKSPACE

      - name: Apply dotfiles
        env:
          HOME: ~/test-home
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
        run: |
          chezmoi apply -v

      - name: Verify installation
        env:
          HOME: ~/test-home
        run: |
          ls -la ~/test-home
          chezmoi verify

      - name: Test shell configuration
        env:
          HOME: ~/test-home
        run: |
          test -f ~/test-home/.zshrc && echo "ZSH config exists"
          test -d ~/test-home/Makefile && echo "Makefile exists"
