name: Test Dotfiles
on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '0 8 * * 6'

jobs:
  test:
    strategy:
      matrix:
        include:
          - name: macOS
            os: macos-latest
          - name: Ubuntu
            os: ubuntu-latest
      fail-fast: false

    name: Test on ${{ matrix.name }}
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Install 1Password CLI
        uses: 1password/install-cli-action@v1

      - name: Set up chezmoi
        id: cache-chezmoi
        uses: actions/cache@v4
        with:
          path: ~/bin/chezmoi
          key: ${{ runner.os }}-chezmoi-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-chezmoi-
